### ISSUE TITLE
Please add a README file

### ISSUE THREAD

**Issue by lainq** [electric-package-manager/docs#1]
Please add a README file that has links to all other documentations 🙂

**Comment by lainq** [comment]
🤷🏾‍♂️

**Comment by suptejas** [comment]
@pranavbaburaj I can't do that because this repository is automatically rendered onto the website. Hence I can't add a README.md. I closed this issue because I added a link to documentation and a description on the tagline of the repo.

**Comment by lainq** [comment]
> @pranavbaburaj I can't do that because this repository is automatically rendered onto the website. Hence I can't add a README.md. I closed this issue because I added a link to documentation and a description on the tagline of the repo.

Oh, I didn't know that. Thank you :smile:
